language: node_js
after_success:
  # Add ssh key to allow git push and then deploy to GH pages
  - |

       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

       # Decrypt the file containing the private key
       openssl aes-256-cbc \
         -K $encrypted_853232ab0902_key \
         -iv $encrypted_853232ab0902_iv \
         -in ".travis/github_deploy_key.enc" \
         -out "$SSH_FILE" -d

       # Enable SSH authentication
       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config
  - npm run deploy
